spring:
  application:
    name: SpringStarter

  datasource:
    url: jdbc:mysql://localhost:3306/springmvc?useUnicode=true&characterEncoding=utf8
    username: root
    password: 새비번
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  web:
    locale: ko_KR
    locale-resolver: fixed

server:
  servlet:
    context-path: /springStarter
    encoding:
      charset: UTF-8
      enabled: true
      force: true